### PR TITLE
Add config allowable_chars 

### PR DESCRIPTION
**Pull request by romuCho**
allowable_chars config to not split keywords with this chars : for insert Database or for search in website.

### CODE REVIEW

**Comment by smeeckaert** [comment]
I think it's missing a default value for allowable_chars, both in the constructor of search.php and in the configuration file.

**Comment by romuCho** [comment]
Exactly ! sorry dady !

**Comment by romuCho** [comment]
Du coup ça en est où ?

**Comment by jguyomard** [comment]
:+1:

**Pull request merged**
